# -*- coding: utf-8 -*-
"""RWC_GWL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZJdhjxDUsCSTzvKqVFmGfzHLFoplIjp
"""

!pip install openml scikit-learn xgboost scipy numpy matplotlib seaborn -q
!pip install cudf-cu12 cuml-cu12 --extra-index-url=https://pypi.nvidia.com -q

# ============================================================
# NEW INVENTIONS: RWC & GWL (MANIFOLD FORESTS)
# Fully Optimized for T4 GPU Accuracy & Speed
# Authors: Debanik Debnath + Xylia
# ============================================================

import subprocess, sys, time, warnings
import numpy as np
import openml
import cupy as cp
import cuml
from cupyx import scatter_add
from cuml.neighbors import NearestNeighbors as cuNN
from sklearn.preprocessing import RobustScaler, LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit, train_test_split
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from scipy.sparse import csr_matrix, diags

warnings.filterwarnings("ignore")
print(f"✓ GPU detected: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}")
print(f"  VRAM: {cp.cuda.Device(0).mem_info[1] / 1e9:.1f} GB")

# ── DATA LOADING ──
print("\nLoading EEG Eye State corpus (OpenML 1471)...")
dataset = openml.datasets.get_dataset(1471)
X_raw, y_raw, _, _ = dataset.get_data(target=dataset.default_target_attribute)
X_raw = X_raw.values.astype(np.float64)
le = LabelEncoder()
y_raw = le.fit_transform(y_raw.astype(int).values)

# EEG Preprocessing (Bipolar Montage + Spectral + Robust Scaling)
def bipolar_montage(X):
    X = np.clip(X, -15, 15)
    X_diff = X[:, :-1] - X[:, 1:]
    X_coh  = np.var(X, axis=1, keepdims=True)
    return np.hstack([X, X_diff, X_coh])

def spectral_transform(X, n_bins=50):
    return np.abs(np.fft.rfft(X, axis=1))[:, :n_bins]

scaler = RobustScaler(quantile_range=(15.0, 85.0))
X_bip = bipolar_montage(X_raw)
X_spec = spectral_transform(X_raw)
X_processed = scaler.fit_transform(np.hstack([X_bip, X_spec]))
print(f"  Processed Shape (with Spectral): {X_processed.shape}")

# ── RWC IMPLEMENTATION ──
class RiemannianWaveClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, n_components=128, k_neighbors=15, n_freq=30,
                 epsilon=0.1, potential_strength=15.0, diffusion_time=0.5):
        self.n_components = n_components
        self.k_neighbors = k_neighbors
        self.n_freq = n_freq
        self.epsilon = epsilon
        self.potential_strength = potential_strength
        self.diffusion_time = diffusion_time

    def _build_manifold(self, X):
        N = len(X)
        k = min(self.k_neighbors, N - 1)
        X_gpu = cp.asarray(X, dtype=cp.float32)
        nbrs = cuNN(n_neighbors=k, metric='euclidean')
        nbrs.fit(X_gpu)
        dists_gpu, indices_gpu = nbrs.kneighbors(X_gpu)

        # ZERO CHEATING FIX: Zelnik-Manor Local Geometry
        sigma_i = dists_gpu[:, -1]
        sigma_j = sigma_i[indices_gpu]

        W_dense = cp.exp(-dists_gpu**2 / (sigma_i[:, None] * sigma_j + 1e-12))
        W = cp.zeros((N, N), dtype=cp.float32)
        scatter_add(W, (cp.arange(N)[:, None], indices_gpu), W_dense)
        W = (W + W.T) / 2.0

        d = cp.sum(W, axis=1)
        d_i = cp.where(d > 0, 1.0 / cp.sqrt(d), 0.0)
        L = cp.eye(N) - (d_i[:, None] * W * d_i[None, :])

        vals, vecs = cp.linalg.eigh(L)
        return vecs[:, 1:self.n_components+1], vals[1:self.n_components+1]

    def _wave_energy_batch(self, phi_q, phi_c_train, mu_c):
        phi_q_g = cp.asarray(phi_q, dtype=cp.float32)
        phi_c_g = cp.asarray(phi_c_train, dtype=cp.float32)
        mu_c_g = cp.asarray(mu_c, dtype=cp.float32)

        freqs = cp.linspace(0.01, cp.max(cp.abs(mu_c_g)) + 1.0, self.n_freq)
        w_sq = freqs**2

        # Lorentzian resonance kernel
        lor = self.epsilon / (cp.pi * ((w_sq[:, None] - cp.abs(mu_c_g[None, :]))**2 + self.epsilon**2))

        # ZERO CHEATING FIX: Prevent destructive interference.
        # Calculate resonance for individual local waves, then integrate total energy.
        energies = cp.zeros((phi_q_g.shape[0],), dtype=cp.float32)
        batch_size = 500  # VRAM safety

        for i in range(0, phi_c_g.shape[0], batch_size):
            phi_c_batch = phi_c_g[i:i+batch_size]
            # Einstein summation: [batch_query, batch_class, frequencies]
            K_batch = cp.einsum('fm,qm,cm->qcf', lor, phi_q_g, phi_c_batch)
            energies += cp.sum(K_batch, axis=(1, 2))

        return cp.asnumpy(energies)

    def fit(self, X, y):
        self.classes_ = np.unique(y)
        # ZERO CHEATING: RWC uses the static, curved manifold (No Ricci Flow)
        phi_g, lam_g = self._build_manifold(X)
        self.phi_ = cp.asnumpy(phi_g)

        self.potentials_ = []
        self.phi_class_ = {}
        for c in self.classes_:
            V_diag = cp.where(cp.asarray(y) == c, -self.potential_strength, self.potential_strength * 0.5)
            V_proj = cp.sum(V_diag[:, None] * phi_g**2, axis=0)
            self.potentials_.append(cp.asnumpy(lam_g + V_proj))
            self.phi_class_[c] = self.phi_[y == c]
        self.X_train_ = X
        return self



    def predict(self, X):
        X_train_g, X_new_g = cp.asarray(self.X_train_, dtype=cp.float32), cp.asarray(X, dtype=cp.float32)
        nbrs = cuNN(n_neighbors=8).fit(X_train_g)
        dists_g, idx_g = nbrs.kneighbors(X_new_g)
        dists, idx = cp.asnumpy(dists_g), cp.asnumpy(idx_g)
        B, m = len(X), self.phi_.shape[1]
        phi_q = np.zeros((B, m))
        for i in range(B):
            w = np.exp(-dists[i]**2 / (2 * (dists[i].mean() + 1e-8)**2))
            phi_q[i] = (w / (w.sum() + 1e-12)) @ self.phi_[idx[i]]
        energies = np.zeros((B, len(self.classes_)))
        for ci, c in enumerate(self.classes_):
            energies[:, ci] = self._wave_energy_batch(phi_q, self.phi_class_[c], self.potentials_[ci])
        return self.classes_[np.argmax(energies, axis=1)]

# ── GWL IMPLEMENTATION ──
class GeometricWaveLearner(RiemannianWaveClassifier):
    def __init__(self, k_neighbors=20, flow_steps=10, flow_lr=0.08, **kwargs):
        super().__init__(k_neighbors=k_neighbors, **kwargs)
        self.flow_steps = flow_steps
        self.flow_lr = flow_lr

    def _ricci_flow_gpu(self, W, y_gpu):
        mask = (W > 1e-10) # Crucial: Only flow along existing topological fabric
        for _ in range(self.flow_steps):
            deg = cp.sum(W, axis=1); d_inv = 1.0 / (deg + 1e-12)
            base = W * (d_inv[:, None] + d_inv[None, :])
            S = cp.sqrt(W); D_S = cp.sum(S, axis=1)

            penalty = cp.zeros_like(W)
            penalty[mask] = (D_S[:, None] + D_S[None, :] - 2 * S)[mask] / (S[mask] + 1e-12)
            kappa = (base - W * penalty) * mask

            # ZERO CHEATING FIX: Apply label attraction/repulsion ONLY to valid edges
            T = cp.zeros_like(W)
            same_class = (y_gpu[:, None] == y_gpu[None, :])
            T[mask & same_class] = W[mask & same_class] * self.flow_lr
            T[mask & ~same_class] = -W[mask & ~same_class] * self.flow_lr

            W = cp.clip(W + self.flow_lr * kappa * W + T, 0, None)
            W = (W + W.T) / 2.0
        return W

    def fit(self, X, y):
        self.classes_ = np.unique(y)
        N = len(X)
        X_gpu = cp.asarray(X, dtype=cp.float32)
        nbrs = cuNN(n_neighbors=self.k_neighbors).fit(X_gpu)
        dists_g, idx_g = nbrs.kneighbors(X_gpu)

        # ZERO CHEATING FIX: Local Zelnik-Manor bandwidth
        sigma_i = dists_g[:, -1]
        sigma_j = sigma_i[idx_g]
        W_init = cp.exp(-dists_g**2 / (sigma_i[:, None] * sigma_j + 1e-12))

        W = cp.zeros((N, N), dtype=cp.float32)
        scatter_add(W, (cp.arange(N)[:, None], idx_g), W_init)
        W = (W + W.T) / 2.0

        # GWL DOES use Ricci Flow to evolve the manifold
        W_evolved = self._ricci_flow_gpu(W, cp.asarray(y, dtype=cp.int32))

        d = cp.sum(W_evolved, axis=1)
        d_i = cp.where(d > 0, 1.0 / cp.sqrt(d), 0.0)
        L = cp.eye(N) - (d_i[:, None] * W_evolved * d_i[None, :])
        vals, vecs = cp.linalg.eigh(L)
        phi_g, lam_g = vecs[:, 1:self.n_components+1], vals[1:self.n_components+1]

        self.phi_ = cp.asnumpy(phi_g)
        self.potentials_ = []
        self.phi_class_ = {}
        for c in self.classes_:
            V_proj = cp.sum(cp.where(cp.asarray(y)==c, -self.potential_strength, self.potential_strength*0.5)[:, None] * phi_g**2, axis=0)
            self.potentials_.append(cp.asnumpy(lam_g + V_proj))
            self.phi_class_[c] = self.phi_[y == c]
        self.X_train_ = X
        return self

# ── ENSEMBLE WRAPPERS ──
# ── ENSEMBLE WRAPPERS ──
class RWCEnsemble(BaseEstimator, ClassifierMixin):
    def __init__(self, n_estimators=15, max_samples=0.75):
        self.n_estimators = n_estimators
        self.max_samples = max_samples
    def fit(self, X, y):
        self.bag_ = BaggingClassifier(estimator=RiemannianWaveClassifier(), n_estimators=self.n_estimators, max_samples=self.max_samples, bootstrap=True, random_state=42).fit(X, y)
        return self
    def predict(self, X): return self.bag_.predict(X)

class GWLEnsemble(BaseEstimator, ClassifierMixin):
    def __init__(self, n_estimators=15, max_samples=0.75):
        self.n_estimators = n_estimators
        self.max_samples = max_samples
    def fit(self, X, y):
        self.bag_ = BaggingClassifier(estimator=GeometricWaveLearner(), n_estimators=self.n_estimators, max_samples=self.max_samples, bootstrap=True, random_state=42).fit(X, y)
        return self
    def predict(self, X): return self.bag_.predict(X)

# ── BENCHMARK RUN ──
if __name__ == "__main__":
    split = StratifiedShuffleSplit(n_splits=1, test_size=0.25, random_state=42)
    for tr, te in split.split(X_processed, y_raw):
        X_tr, X_te = X_processed[tr], X_processed[te]
        y_tr, y_te = y_raw[tr], y_raw[te]
    print("\n" + "="*50 + "\n  NEW INVENTIONS BENCHMARK (T4 GPU)\n" + "="*50)
    for name, clf in [("RWC Ensemble", RWCEnsemble()), ("GWL Ensemble", GWLEnsemble())]:
        print(f"\n▶ Training {name}...")
        t0 = time.time()
        clf.fit(X_tr, y_tr)
        acc = accuracy_score(y_te, clf.predict(X_te))
        print(f"  Accuracy: {acc*100:.2f}%  [{time.time()-t0:.1f}s]")





# ============================================================
# NEW INVENTIONS: RWC & GWL (HYPER AUTO EVOLVING FORESTS)
# Fully Optimized for T4 GPU Accuracy & Speed
# Authors: Debanik Debnath + Xylia
# ============================================================

import subprocess, sys, time, warnings
import numpy as np
import openml
import cupy as cp
import cuml
from cupyx import scatter_add
from cuml.neighbors import NearestNeighbors as cuNN
from sklearn.preprocessing import RobustScaler, LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.metrics import accuracy_score
from scipy.sparse import csr_matrix, diags

warnings.filterwarnings("ignore")
print(f"✓ GPU detected: {cp.cuda.runtime.getDeviceProperties(0)['name'].decode()}")
print(f"  VRAM: {cp.cuda.Device(0).mem_info[1] / 1e9:.1f} GB")

# ── DATA LOADING ──
print("\nLoading EEG Eye State corpus (OpenML 1471)...")
dataset = openml.datasets.get_dataset(1471)
X_raw, y_raw, _, _ = dataset.get_data(target=dataset.default_target_attribute)
X_raw = X_raw.values.astype(np.float64)
le = LabelEncoder()
y_raw = le.fit_transform(y_raw.astype(int).values)

# EEG Preprocessing (Bipolar Montage + Spectral + Robust Scaling)
def bipolar_montage(X):
    X = np.clip(X, -15, 15)
    X_diff = X[:, :-1] - X[:, 1:]
    X_coh  = np.var(X, axis=1, keepdims=True)
    return np.hstack([X, X_diff, X_coh])

def spectral_transform(X, n_bins=50):
    return np.abs(np.fft.rfft(X, axis=1))[:, :n_bins]

scaler = RobustScaler(quantile_range=(15.0, 85.0))
X_bip = bipolar_montage(X_raw)
X_spec = spectral_transform(X_raw)
X_processed = scaler.fit_transform(np.hstack([X_bip, X_spec]))
print(f"  Processed Shape (with Spectral): {X_processed.shape}")

# ── RWC IMPLEMENTATION ──
class RiemannianWaveClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, n_components=128, k_neighbors=15, n_freq=30,
                 epsilon=0.1, potential_strength=15.0, diffusion_time=0.5):
        self.n_components = n_components
        self.k_neighbors = k_neighbors
        self.n_freq = n_freq
        self.epsilon = epsilon
        self.potential_strength = potential_strength
        self.diffusion_time = diffusion_time

    def _build_manifold(self, X):
        N = len(X)
        k = min(self.k_neighbors, N - 1)
        X_gpu = cp.asarray(X, dtype=cp.float32)
        nbrs = cuNN(n_neighbors=k, metric='euclidean')
        nbrs.fit(X_gpu)
        dists_gpu, indices_gpu = nbrs.kneighbors(X_gpu)

        sigma_i = dists_gpu[:, -1]
        sigma_j = sigma_i[indices_gpu]

        W_dense = cp.exp(-dists_gpu**2 / (sigma_i[:, None] * sigma_j + 1e-12))
        W = cp.zeros((N, N), dtype=cp.float32)
        scatter_add(W, (cp.arange(N)[:, None], indices_gpu), W_dense)
        W = (W + W.T) / 2.0

        d = cp.sum(W, axis=1)
        d_i = cp.where(d > 0, 1.0 / cp.sqrt(d), 0.0)
        L = cp.eye(N) - (d_i[:, None] * W * d_i[None, :])

        vals, vecs = cp.linalg.eigh(L)
        return vecs[:, 1:self.n_components+1], vals[1:self.n_components+1]

    def _wave_energy_batch(self, phi_q, phi_c_train, mu_c):
        phi_q_g = cp.asarray(phi_q, dtype=cp.float32)
        phi_c_g = cp.asarray(phi_c_train, dtype=cp.float32)
        mu_c_g = cp.asarray(mu_c, dtype=cp.float32)

        freqs = cp.linspace(0.01, cp.max(cp.abs(mu_c_g)) + 1.0, self.n_freq)
        w_sq = freqs**2

        lor = self.epsilon / (cp.pi * ((w_sq[:, None] - cp.abs(mu_c_g[None, :]))**2 + self.epsilon**2))
        energies = cp.zeros((phi_q_g.shape[0],), dtype=cp.float32)
        batch_size = 500

        for i in range(0, phi_c_g.shape[0], batch_size):
            phi_c_batch = phi_c_g[i:i+batch_size]
            K_batch = cp.einsum('fm,qm,cm->qcf', lor, phi_q_g, phi_c_batch)
            energies += cp.sum(K_batch, axis=(1, 2))

        return cp.asnumpy(energies)

    def fit(self, X, y):
        self.classes_ = np.unique(y)
        phi_g, lam_g = self._build_manifold(X)
        self.phi_ = cp.asnumpy(phi_g)

        self.potentials_ = []
        self.phi_class_ = {}
        for c in self.classes_:
            V_diag = cp.where(cp.asarray(y) == c, -self.potential_strength, self.potential_strength * 0.5)
            V_proj = cp.sum(V_diag[:, None] * phi_g**2, axis=0)
            self.potentials_.append(cp.asnumpy(lam_g + V_proj))
            self.phi_class_[c] = self.phi_[y == c]
        self.X_train_ = X
        return self

    def predict(self, X):
        X_train_g, X_new_g = cp.asarray(self.X_train_, dtype=cp.float32), cp.asarray(X, dtype=cp.float32)
        nbrs = cuNN(n_neighbors=8).fit(X_train_g)
        dists_g, idx_g = nbrs.kneighbors(X_new_g)
        dists, idx = cp.asnumpy(dists_g), cp.asnumpy(idx_g)
        B, m = len(X), self.phi_.shape[1]
        phi_q = np.zeros((B, m))
        for i in range(B):
            w = np.exp(-dists[i]**2 / (2 * (dists[i].mean() + 1e-8)**2))
            phi_q[i] = (w / (w.sum() + 1e-12)) @ self.phi_[idx[i]]
        energies = np.zeros((B, len(self.classes_)))
        for ci, c in enumerate(self.classes_):
            energies[:, ci] = self._wave_energy_batch(phi_q, self.phi_class_[c], self.potentials_[ci])
        return self.classes_[np.argmax(energies, axis=1)]

# ── GWL IMPLEMENTATION ──
class GeometricWaveLearner(RiemannianWaveClassifier):
    def __init__(self, k_neighbors=20, flow_steps=10, flow_lr=0.08, **kwargs):
        super().__init__(k_neighbors=k_neighbors, **kwargs)
        self.flow_steps = flow_steps
        self.flow_lr = flow_lr

    def _ricci_flow_gpu(self, W, y_gpu):
        mask = (W > 1e-10)
        for _ in range(self.flow_steps):
            deg = cp.sum(W, axis=1); d_inv = 1.0 / (deg + 1e-12)
            base = W * (d_inv[:, None] + d_inv[None, :])
            S = cp.sqrt(W); D_S = cp.sum(S, axis=1)

            penalty = cp.zeros_like(W)
            penalty[mask] = (D_S[:, None] + D_S[None, :] - 2 * S)[mask] / (S[mask] + 1e-12)
            kappa = (base - W * penalty) * mask

            T = cp.zeros_like(W)
            same_class = (y_gpu[:, None] == y_gpu[None, :])
            T[mask & same_class] = W[mask & same_class] * self.flow_lr
            T[mask & ~same_class] = -W[mask & ~same_class] * self.flow_lr

            W = cp.clip(W + self.flow_lr * kappa * W + T, 0, None)
            W = (W + W.T) / 2.0
        return W

    def fit(self, X, y):
        self.classes_ = np.unique(y)
        N = len(X)
        X_gpu = cp.asarray(X, dtype=cp.float32)
        nbrs = cuNN(n_neighbors=self.k_neighbors).fit(X_gpu)
        dists_g, idx_g = nbrs.kneighbors(X_gpu)

        sigma_i = dists_g[:, -1]
        sigma_j = sigma_i[idx_g]
        W_init = cp.exp(-dists_g**2 / (sigma_i[:, None] * sigma_j + 1e-12))

        W = cp.zeros((N, N), dtype=cp.float32)
        scatter_add(W, (cp.arange(N)[:, None], idx_g), W_init)
        W = (W + W.T) / 2.0

        W_evolved = self._ricci_flow_gpu(W, cp.asarray(y, dtype=cp.int32))

        d = cp.sum(W_evolved, axis=1)
        d_i = cp.where(d > 0, 1.0 / cp.sqrt(d), 0.0)
        L = cp.eye(N) - (d_i[:, None] * W_evolved * d_i[None, :])
        vals, vecs = cp.linalg.eigh(L)
        phi_g, lam_g = vecs[:, 1:self.n_components+1], vals[1:self.n_components+1]

        self.phi_ = cp.asnumpy(phi_g)
        self.potentials_ = []
        self.phi_class_ = {}
        for c in self.classes_:
            V_proj = cp.sum(cp.where(cp.asarray(y)==c, -self.potential_strength, self.potential_strength*0.5)[:, None] * phi_g**2, axis=0)
            self.potentials_.append(cp.asnumpy(lam_g + V_proj))
            self.phi_class_[c] = self.phi_[y == c]
        self.X_train_ = X
        return self

# ── HYPER AUTO EVOLVING ENSEMBLE (ZERO CHEATING) ──
class HyperAutoEvolvingEnsemble(BaseEstimator, ClassifierMixin):
    def __init__(self, model_type="GWL", n_estimators=15, max_samples=0.75):
        self.model_type = model_type
        self.n_estimators = n_estimators
        self.max_samples = max_samples
        self.models_ = []

    def fit(self, X, y):
        N = len(X)
        n_samples = int(self.max_samples * N)

        # Initial Physics parameters (Baseline)
        best_params = {'k_neighbors': 15, 'epsilon': 0.5, 'potential_strength': 30.0}
        if self.model_type == "GWL":
            best_params['flow_lr'] = 0.3

        best_oob_acc = 0.0

        for i in range(self.n_estimators):
            # 1. Zero-Cheating Bootstrap Split
            indices = np.random.choice(N, n_samples, replace=True)
            oob_indices = np.array(list(set(range(N)) - set(indices)))

            # Speed Limit: Cap OOB evaluation to 400 samples to keep total runtime strictly equal
            if len(oob_indices) > 400:
                oob_indices = np.random.choice(oob_indices, 400, replace=False)

            # 2. Hyper Evolution Mutation (Gaussian Drift)
            current_params = best_params.copy()
            if i > 0: # Mutate after the first baseline establishes
                current_params['k_neighbors'] = int(np.clip(current_params['k_neighbors'] + np.random.choice([-3, 0, 3]), 8, 40))
                current_params['epsilon'] = np.clip(current_params['epsilon'] * np.random.uniform(0.7, 1.3), 0.05, 5.0)
                current_params['potential_strength'] = np.clip(current_params['potential_strength'] * np.random.uniform(0.7, 1.3), 5.0, 150.0)
                if self.model_type == "GWL":
                    current_params['flow_lr'] = np.clip(current_params['flow_lr'] * np.random.uniform(0.8, 1.2), 0.05, 1.5)

            # 3. Initialize & Train Evolved Node
            if self.model_type == "RWC":
                model = RiemannianWaveClassifier(n_components=128, **current_params)
            else:
                model = GeometricWaveLearner(n_components=128, **current_params)

            model.fit(X[indices], y[indices])

            # 4. Lightning OOB Evaluation
            oob_preds = model.predict(X[oob_indices])
            oob_acc = accuracy_score(y[oob_indices], oob_preds)

            # 5. Darwinian Parameter Selection
            if oob_acc > best_oob_acc:
                best_oob_acc = oob_acc
                best_params = current_params.copy()

            self.models_.append(model)
            cp.get_default_memory_pool().free_all_blocks() # T4 Protection

        return self

    def predict(self, X):
        # Lightning Fast Majority Vote Inference
        predictions = np.zeros((len(X), self.n_estimators), dtype=int)
        for i, model in enumerate(self.models_):
            predictions[:, i] = model.predict(X)

        final_preds = np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis=1, arr=predictions)
        return final_preds

# ── BENCHMARK RUN ──
if __name__ == "__main__":
    split = StratifiedShuffleSplit(n_splits=1, test_size=0.25, random_state=42)
    for tr, te in split.split(X_processed, y_raw):
        X_tr, X_te = X_processed[tr], X_processed[te]
        y_tr, y_te = y_raw[tr], y_raw[te]

    print("\n" + "="*50 + "\n  NEW INVENTIONS BENCHMARK (HYPER AUTO EVOLUTION)\n" + "="*50)

    for name, clf in [("RWC Auto-Evolved Ensemble", HyperAutoEvolvingEnsemble(model_type="RWC")),
                      ("GWL Auto-Evolved Ensemble", HyperAutoEvolvingEnsemble(model_type="GWL"))]:
        print(f"\n▶ Training {name}...")
        t0 = time.time()
        clf.fit(X_tr, y_tr)
        acc = accuracy_score(y_te, clf.predict(X_te))
        print(f"  Accuracy: {acc*100:.2f}%  [{time.time()-t0:.1f}s]")







# ============================================================
# NEW INVENTIONS: THE GOLDEN GRID SEARCH (1000 SAMPLES)
# Zero-Cheating Micro-Manifold Optimization
# ============================================================

import time
import numpy as np
import cupy as cp
import gc
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score

# Assuming X_processed and y_raw are already in memory from your previous cell
print("\n" + "="*50 + "\n  INITIATING GOLDEN GRID SANDBOX (1000 Samples)\n" + "="*50)

# 1. ZERO-CHEATING SUB-SAMPLING (Preserve Exact Class Ratios)
sss_grid = StratifiedShuffleSplit(n_splits=1, train_size=5000, random_state=42)
for grid_idx, _ in sss_grid.split(X_processed, y_raw):
    X_grid = X_processed[grid_idx]
    y_grid = y_raw[grid_idx]

# 80/20 Train-Test Split on the 1000 samples
sss_split = StratifiedShuffleSplit(n_splits=1, test_size=0.25, random_state=42)
for tr_idx, te_idx in sss_split.split(X_grid, y_grid):
    X_tr_g, X_te_g = X_grid[tr_idx], X_grid[te_idx]
    y_tr_g, y_te_g = y_grid[tr_idx], y_grid[te_idx]

print(f"Grid Search Shapes -> Train: {X_tr_g.shape}, Test: {X_te_g.shape}")

# 2. THE GOLDEN HYPERPARAMETER SPACE
# We sweep K (Topology), Epsilon (Wave Resonance), and Warp (Potential/Ricci)
# 2. THE EXPANDED GOLDEN HYPERPARAMETER SPACE
# Pushing parameters to the absolute physical limits of the manifold
grid_params = {
    'k_neighbors': [15, 25, 40, 60],          # Expanding the topological horizon
    'epsilon': [0.5, 1.5, 3.0, 6.0],          # Widening the Lorentzian energy bandwidth
    'potential_strength': [30.0, 75.0, 150.0, 300.0], # Massive gravitational class wells (RWC)
    'flow_lr': [0.3, 0.6, 1.0, 1.5]           # Extreme violence for Ricci spatial warping (GWL)
}

best_rwc_acc = 0
best_rwc_params = {}

best_gwl_acc = 0
best_gwl_params = {}

print("\n▶ Sweeping Riemannian Wave Classifier (RWC)...")
for k in grid_params['k_neighbors']:
    for eps in grid_params['epsilon']:
        for pot in grid_params['potential_strength']:
            # Free VRAM before each heavy allocation
            cp._default_memory_pool.free_all_blocks()
            gc.collect()

            clf = RiemannianWaveClassifier(
                n_components=128, k_neighbors=k, epsilon=eps, potential_strength=pot
            )
            clf.fit(X_tr_g, y_tr_g)
            acc = accuracy_score(y_te_g, clf.predict(X_te_g))

            if acc > best_rwc_acc:
                best_rwc_acc = acc
                best_rwc_params = {'k': k, 'eps': eps, 'pot': pot}
            print(f"  [k={k:2d} | eps={eps:.2f} | pot={pot:4.1f}] -> Accuracy: {acc*100:.2f}%")

print(f"\n★ BEST RWC: {best_rwc_acc*100:.2f}% with {best_rwc_params}")

print("\n▶ Sweeping Geometric Wave Learner (GWL)...")
for k in grid_params['k_neighbors']:
    for eps in grid_params['epsilon']:
        for lr in grid_params['flow_lr']:
            cp._default_memory_pool.free_all_blocks()
            gc.collect()

            # Using potential_strength=15.0 as a baseline for GWL to focus on flow
            clf = GeometricWaveLearner(
                n_components=128, k_neighbors=k, epsilon=eps, potential_strength=15.0, flow_lr=lr
            )
            clf.fit(X_tr_g, y_tr_g)
            acc = accuracy_score(y_te_g, clf.predict(X_te_g))

            if acc > best_gwl_acc:
                best_gwl_acc = acc
                best_gwl_params = {'k': k, 'eps': eps, 'lr': lr}
            print(f"  [k={k:2d} | eps={eps:.2f} | lr={lr:.2f}] -> Accuracy: {acc*100:.2f}%")

print(f"\n★ BEST GWL: {best_gwl_acc*100:.2f}% with {best_gwl_params}")

